version: "3.8"

services:
  esp32:
    build:
      context: .
      dockerfile: Dockerfile
    image: esp32-idf-dev
    user: "${UID}:${GID}"
    container_name: esp32-idf
    working_dir: /work
    volumes:
      - ./project:/work
      - idf-cache:/root/.espressif

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true
    stdin_open: true
    environment:
      - IDF_PATH=/opt/esp/idf
      - HOME=/home/dev
      - TERM=xterm-256color
volumes:
  idf-cache:
